{
  homePage {
    featured {
      name
      slug
      price
      discount
      image {
        url
      }
    }
    reviews {
      photo {
        url
      }
      username
      body
    }
  }
}
