{
  products {
    id
    name
    slug
    price
    discount
    category {
      id
      name
    }
    brand {
      id
      name
    }
    image {
      url
    }
  }
  categories {
    name
    icon
    id
  }
  brands {
    name
    logo {
      url
    }
    id
  }
}
